FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt update -y -q && apt upgrade -y -q && apt update -y -q && \
    apt install -y -q \
    bison \
    build-essential \
    cmake \
    curl \
    git \
    libunwind-dev \
    libzstd-dev \
    llvm-12-dev \
    ninja-build \
    patchelf \
    python-is-python3 \
    python3 \
    re2c \
    unzip \
    xz-utils \
    zlib1g-dev

RUN mkdir -p /root
COPY lfortran /root/
COPY common.sh /root/

WORKDIR /root
