FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt update -y -q && apt upgrade -y -q && apt update -y -q && \
    apt install -y -q \
    build-essential \
    ca-certificates \
    cmake \
    git \
    ninja-build \
    python3 \
    xz-utils

RUN mkdir -p /root
COPY edg /root/
COPY common.sh /root/

WORKDIR /root
