FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN dpkg --add-architecture i386
RUN apt update -y -q && apt upgrade -y -q && apt update -y -q && \
    apt install -y -q \
    build-essential \
    bison \
    curl \
    flex \
    git \
    libc6-dev-i386 \
    libc6-dev:i386 \
    make \
    patchelf \
    xz-utils

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

RUN mkdir -p /root
COPY lc3 /root/
COPY common.sh /root/

WORKDIR /root
